name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Go env
        run: |
          go env

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verify Docker is available
        run: |
          docker version
          docker info

      - name: Download dependencies
        run: go mod download

      - name: Run tests (with Docker / testcontainers)
        env:
          TESTCONTAINERS_RYUK_DISABLED: 'false'
        run: |
          go test ./... -v
